config/routes.rb
Drive::Application.routes.draw do

  resources :abuse_reports

  resources :manage_bodyindices do
    collection do
        delete 'destroy_multiple'
    end
  end

  resources :abuse_categories

  resources :contactadmins

  resources :messages do
    collection do
      get :trash_messages
      get :sent_messages
      put :move_all_to_trash_recipient
      put :delete_all_by_sender
    end
    
    member do
     post :trash
     post :destroy_recipient
     post :destroy_sender
     get :reply
    end
  end

 resources :friendships do
  member do
     post :accept
     post :decline
     post :delete
     post :cancel
  end
 end

 resources :shared do
    collection do
      get :search
      get :all_car
      get :car_body_index
    end
  end

  resources :blog_comments

  resources :notifications do 
    collection do
      get :noti_delete
    end
  end
  
  resources :comment_logs
  match "logbooks/:id/user_logbook"  => 'favourites#user_logbook'

  match "user_blogs/:id/user_blog"  => 'favourites#user_blog'

  match "carprofiles/:id/mycarprofile"  => 'favourites#mycarprofile'
 
  resources :comment_logbooks

  resources :user_blogs do
    collection do 
      post :like_blog
      get :like_count
      get :all_blogs
    end
  end

  resources :comments
  resources :new_cars
  resources :favourites do
    collection do
      get :deletefav
    end
  end

   resources :egifts ,:only => [:index] do
     resources :send_gifts
     collection do
      get :my_gifts
      get :anonymous
      get :personal
      get :egift_notifications
     end
   end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
  authenticated :user do
    root :to => 'home#index'
  end
  unauthenticated :user do
    root :to => 'devise/registrations#new'
  end
 end

  devise_for :admins

  resources :users,  :only => [:index,:destroy,:show,:subscribe_profile,:block_user,:unblock_user,:blocked_users,:change_status,:edit,:update,:new,:create] do
  collection    do
      post :subscribe_profile
      get  :user_emails
      post :block_user
      post :unblock_user
      get  :blocked_users
      post :change_status
      get :addpoints
      post :addedpoints
    end
   member do
      get :friend_request
      get :user_friends
      get :user_cars
      get :user_gifts
      get :user_blog
   end
  end
  

 
  match '/users/:id/toggled_status', :to => "users#toggled_status"

  match "/carprofiles/update_model", :to => "carprofiles#update_model"

  match "/carprofiles/update_body", :to => "carprofiles#update_body"

  match "/logbooks/updatemodel", :to => "logbooks#updatemodel"

  match "/logbooks/updatebody", :to => "logbooks#updatebody"

  match "/logbooks/all_logbook", :to => "logbooks#all_logbook"

  match '/pages/:id' => 'pages#show'

  match 'logbooksearch' => 'logbooks#logbooksearch'

  match 'blogsearch' => 'user_blogs#blogsearch'

  match "myfriend"  => 'logbooks#myfriend'

  match "/logbooksearch_home", :to => "home#logbooksearch_home"

  match "myfriend_blog"  => 'user_blogs#myfriend_blog'

  match "/carprofiles/comment_destroy", :to => "carprofiles#comment_destroy"

  match "/credits/get_credits" , :to => "credits#get_credits"

  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    match '/admin_mailer' => 'admin_mailers#admin_mailer'
    resources :pages
    resources :blogs
    resources :seos
    resources :car_makes
    resources :credits
    resources :car_models
    resources :logbook_categories
    resources :egift_categories
    resources :egifts
    resources :engines do 
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :body_indices
    resources :credit_packages
  end

  resources :credits do
    collection do
      get :earn_credits
      get :select_package
    end
  end
  resources :admincontacts
  resources :logbooks do 
    collection do 
      post :like_logbook
      get :like_count
      post :previews
    end
  end
  resources :carprofiles do
    collection do 
      post :like_car
      get :like_count
      post :subscribe_car
      post :spotlight
      post :post_comment
      get :guest_user
    end
  end 
  resources :carprofile_photos

 resources :logbook_categories do 
    get :search, :on => :collection
  end

  resources :blogs do 
    get :search_blog, :on => :collection
  end
 
  root :to => "devise/registrations#new"
   match 'subscribe_count' => 'home#subscribe_count'

  match 'subscar_count' =>'carprofiles#subscar_count'

  
  match '/contact' => 'home#contact'
  match 'search' => 'home#search'
  match 'searchpeople' => 'home#searchpeople'
  match 'keywordsearch' => 'home#keywordsearch'
  match 'topcar' => 'home#topcar'
  match 'paginate_top_car' => 'home#paginate_top_car'

end

app/controllers/home_controller.rb
 require 'will_paginate/array'
 class HomeController < ApplicationController
   before_filter :authenticate_user!

  def index
    @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
    @friends = current_user.friends
    @contactadmins = Contactadmin.find(:all, :order => "created_at DESC")
    @user = @friends.find_all {|u| u.birthday_today?}
    @user_blogs = current_user.user_blogs.all
  end

  def contact
    if request.post? and params[:reset_password]
            if contact = Contact.new(params[:reset_password])
              contact.name = "#{params[:reset_password][:name]}"
              contact.email = "#{params[:reset_password][:email]}"

              contact.subject = "#{params[:reset_password][:subject]}"
              contact.message = "#{params[:reset_password][:message]}"
              if contact.save
              ContactMailer.registration_confirmation(contact).deliver
              flash[:notice] = "Thank You for contacting us. We will reach you back shortly."
              redirect_to("/contact")
              end
            end
	         else
	           @title = "contacts"
	         end
    end

# def search
# @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
# q = params[:q]
# @users=User.search(params[:q]).result.paginate(:page => params[:page],:per_page => 8)
# # @users = User.search(first_name_or_last_name_or_location_or_email_cont: q).result(:distinct => true).paginate(:page => params[:page],:per_page => 8)
# end

def search
    @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
    if params[:user_cont].present?
       @users = User.search(first_name_or_last_name_or_location_or_email_cont: params[:user_cont]).result(:distinct => true).paginate(:page => params[:page],:per_page => 8)
    else
      @users=User.search(params[:country]).result.paginate(:page => params[:page],:per_page => 8)
    end
end


def keywordsearch
q = params[:q]
@users = User.search(first_name_or_last_name_or_nickname_or_location_or_email_cont: q).result
@user_blogs = UserBlog.search(title_cont: q).result
@logbooks = Logbook.search(title_cont: q).result
@carprofiles = Carprofile.search(license_plate_or_engine_dis_or_power__or_cont: q).result
@favourites =  Favourite.search(favourite_type_cont: q).result
end

def subscribe_count
  @user = User.find(params[:id])
  @subscribers =  Subscriber.subscribers(@user,User)
end
  
 def topcar
    @spotlighted_cars = Carprofile.where("spotlighted = ?", true)
    @top_cars = top_cars(Carprofile.all.map(&:id))
    @@cars = @top_cars.to_a
    @car_rank = @@cars
    @top_cars = @top_cars.to_a.take(100)
  end

  def paginate_top_car
    @spotlighted_cars = Carprofile.where("spotlighted = ?", true)
    @car_rank = @@cars
    @top_cars = @@cars.take(100)
    render "topcar"

  end



def logbooksearch_home
  
  @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
  @logbook_categories = LogbookCategory.all
  
  carmake = params[:logbook][:car_make_id]
  carmodel =  params[:logbook][:car_model_id]
  lc = params[:logbook][:logbook_category_id_eq]

  if carmake.empty? #if car make is empty, #search for logbook category
      @logbook = Logbook.search(logbook_category_id_eq: lc).result.paginate(page: params[:page], per_page: 5) 
      @logbooks = @logbook.where(:status => true)
  elsif carmodel.nil? #if car model is nil
    if lc.empty?
      @logbook = Logbook.where("car_make_id = ? ", carmake).paginate(page: params[:page], per_page: 5) 
      @logbooks = @logbook.where(:status => true)
    else
      @logbook = Logbook.where("car_make_id = ? and logbook_category_id = ?", carmake,lc).paginate(page: params[:page], per_page: 5)
       @logbooks = @logbook.where(:status => true)
    end
  else
    if lc.empty? #if logbook category id is nil
      @logbook = Logbook.search(car_make_id_eq: carmake).result.paginate(page: params[:page], per_page: 5)
       @logbooks = @logbook.where(:status => true)
    else
      @logbook = Logbook.where("car_make_id = ? and car_model_id = ? and logbook_category_id = ?", carmake,carmodel,lc).paginate(page: params[:page], per_page: 5)
       @logbooks = @logbook.where(:status => true) 
    end 
  end
end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<h2>Contact Us</h2>

<h4>Send Us An Email</h4>

<%= form_for :reset_password do |f| %>


	<div class="field-row">
		<label>Name	</label><br/>									
		<%= f.text_field :name%>
	</div>

	<div class="field-row">
		<label>Email</label><br/>
		<%= f.text_field :email%>	
	</div>

	<div class="field-row">
		<label>Message</label><br/>
		<%= f.text_area :message%>
	</div>

	
	<%= submit_tag 'Send',:class =>"button2" %>
<%end%>
							

app/views/home/index.html.erb
<div class="middle">
  <div class="container_20" style="background:#333; margin-bottom:10px">
	<%= render 'shared/carousel' %>		
  </div>
		
		
  <%= javascript_include_tag "prototype" %>

    <div class="container_20 profile_bg">
		<div class="grid_4">
	      <div class="profile_image"><!-- <img alt="" src="assets/profile.jpg"> -->
	      	<%= current_user.pic?  ? (image_tag current_user.pic.url(:thumb)) : (image_tag 'profile.jpg')%>
	      </div>
		</div>
	
		<div class="grid_16">
		  <h1><%= current_user.first_name %>&nbsp;<%= current_user.last_name %>&nbsp;
		
		  	<%= image_tag (current_user.visibility_status ? "online.png" : "offline.gif"), :id => "visible_mode" %>
		  </h1>
			<ul class="tab_menu">

				<li><%= link_to "Buy credits(#{current_user.credit.to_i})",select_package_credits_path,:class => "earn_credit"  %></li> 

				<li><%= link_to " My Cars" , carprofiles_path %></li>
				<li><%= link_to "Subscribers",:action=>"subscribe_count",:id=>current_user.id%>
		      </li> 
				<li><a href="<%= messages_path %>">Message</a></li> 
				<li><%= link_to "My Gifts" , my_gifts_egifts_path %></li>
				<li><a href="<%= favourites_path %>"><img src="/assets/star2.png" alt=""></a></li>
				<li><%= select_tag :visibility_status,options_for_select(["VISIBLE","INVISIBLE"],:selected => (current_user.visibility_status ? "VISIBLE" : "INVISIBLE") ),:onchange=>"javascript:user_status(jQuery(\"#visibility_status\").val());", :class=>"pe_tf"%></li>      
			</ul>
		</div>
   </div>
	
	<div class="container_20">
		<div class="grid_9 aboutme" style="word-wrap:break-word;">
	      <h4>About Me</h4>
			<p style="overflow: auto; height: 105px; word-wrap:break-word;">
				<% if current_user.about.nil? || current_user.about.blank? %>
				No Description Yet! (For about me click settings)
				<% else %>
				<%= current_user.about %>
				<% end %>
			</p>
			
	        <div class="black_heading">MY LATEST BLOGS</div>
	
			<div id="comment_load" style="overflow: auto; height: 370px; margin: 10px 0px; word-wrap:break-word;">
				<% @user_blogs.each do |user_blog| %>
					<div class="blog_div2" style="word-wrap:break-word;">
				        <a class="redlink" href="<%= user_blog_path(user_blog) %>"><%=  user_blog.title rescue nil%></a><br>
				        <p style="word-wrap:break-word;">
				        	<%= sanitize raw(user_blog.body)[0..200], :tags => %w(b i u p br) rescue nil %>
				        </p>
				        <a class="bluelink" href="<%= user_blog_path(user_blog) %>">Read More</a>
				    </div>
			    <%end%>
		    </div>
		    </div>

		    
		</div>
        
      <div class="grid_11">
      	<div class="car_description1" >
            <div id="comment_load" style="overflow: auto; height: 80px; margin: 10px 0px;">
			    <table  border="0" cellspacing="0" cellpadding="5">
			      <% @user.each do |u|%>
			        <%unless u.id == current_user.id%>
				      <tr>
				        <td align="left" valign="middle"><img src="/assets/birth.png" alt=""></td>
				        <td width="100%" align="left" valign="middle"><strong><%=u.first_name rescue nil%>'s</strong> Birthday Today</td>
				      </tr>
			        <%else%>
			        <%end%>
			      <%end%>
			 
			      <% @contactadmins.each do |contact|%>
			        <tr>
			          <td align="left" valign="middle"><img src="/assets/newspapers.png" alt="" width="24" height="24"></td>
			          <td align="left" valign="middle" style="word-wrap:break-word;"><b><%= contact.message rescue nil%></b></td>
			        </tr>
			      <%end%>
			    </table>
	        </div>
	    </div>
	    <div class="grid_5" style="float:right">
			<div class="black_heading" style="margin-top:20px">PERSONAL EXPERIENCE</div>
	            <div class="pe_box" style="margin-bottom:10px">
		            <strong>Personal stories, advice and support</strong><br>
					Logbooks from the real car owners - are truth about the experience from the first hands.
					How-to guides with photos, tips and articles on car care and maintenance.  
		            <%= form_tag logbooksearch_home_path, :method => :get do %>
		            <div style="margin-top:10px"><strong>Make</strong>  <span class="red">*</span></div>
		            <div style="width: 190px;">
		               <%= select "logbook",  :car_make_id, CarMake.all.map {|s| [s.name, s.id]},{:prompt => "Select Carmake"}, :onchange => "#{remote_function(:url => {:controller =>"logbooks", :action => "updatemodel"}, :with => "'updatemodel='+value",:loading => "Element.show('loader');",:complete => "Element.hide('loader');")}", :style=>"width:155px" %><br/><br/>

		                <div id="car_make_id" style="width: 190px;">
		                  <%= select "carprofile", :car_model_id,   @car_model.map {|s| [s.name, s.id]},{:prompt => "Select Model"}  ,:onchange => "#{remote_function(:url => {:controller =>"carprofiles", :action => "update_body"}, :with => "'update_body='+value",:loading => "Element.show('loader');",:complete => "Element.hide('loader');")}"  rescue nil %>
		                  <%= image_tag("/assets/loadingg.gif",
		                      :align => "absmiddle",
		                      :border => 0,
		                      :id => "loader",
		                      :style =>"display: none;" ) %>
		                </div>
		            </div>
		            <div ><strong>Topic</strong>  <span class="red">*</span></div>
	                <div>
	                   <%= collection_select :logbook ,:logbook_category_id_eq, LogbookCategory.all ,:id,:name, :prompt => 'Logbook category'%>
	                </div>
	               <div style="margin:10px 0 0 0" ><%= submit_tag "Search",:class=>"submit_btn2"%></div>
	              <%end%>
	            </div>
			</div>
		</div>
	  </div>
	</div>
</div>
		
		

app/views/home/keywordsearch.html.erb
<%= stylesheet_link_tag  "table_style" %>
<div class="middle">
  <div class="grid_20 title">
    <h4 style="margin-top:10px;">Message</h4>
    </div>

<% unless @users.empty? %>
<div class="grid_20" style="margin:10px;">  
<table width="100%">
<tr>
<th>Firstname</th>
<th>Lastname</th>
<th>Email</th>
<th>Location</th>
</tr>
<% @users.each do |user|%>
  <tr>
    <% status = Block.find_by_blockable_id_and_blocker_id(current_user.id,user.id).present? %>
    <% if status %>
     <td><%= link_to user.first_name, "#",:id=>user.id ,:onclick => "alert('You are being Blocked !!!');"%></td>
    <% else %>
    <td><%= link_to user.first_name, user_path(user),:id=>user.id %></td>
    <% end %>    
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.location %></td>
    <%# end %>
  </tr>
<% end %>
</table>
</div>
<% end %>

<% unless @user_blogs.empty? %>
<div class="grid_20" style="margin:10px;"> 
<table width="100%">
<tr>
<th>UserblogTitle</th>
</tr>
  <% @user_blogs.each do |user_blog| %>
  <tr>
    <td><%= link_to user_blog.title,:controller=>"user_blogs",:action=>"show",:id=>user_blog.id %></td>
  </tr>
    <% end %>
</table>
</div>
<% end %>


 <% unless @logbooks.empty? %>
<div class="grid_20" style="margin:10px;"> 
<table width="100%">
<tr>
<th>LogbookTitle</th>
</tr>
   <% @logbooks.each do |logbook| %>
  <tr>
    <td><%= link_to logbook.title,:controller=>"logbooks",:action=>"show",:id=>logbook.id rescue nil%></td>
  </tr>
    <% end %>
</table>
</div>
<% end %>


<% unless @favourites.empty? %> 
<div class="grid_20" style="margin:10px;">
<table width="100%">
<tr>
<th>Favouritetype</th>
</tr>

<% @favourites.each do |n| %>
<tr>
  <%#  user = User.find(n.user_id)%>
    <%if n.favourite_type == "favourite_logbook"%>
       <%#= raise @favourites.inspect %>
      <td><%= link_to n.logbook.title,logbook_path(n.logbook_id) rescue nil %></td>
    <% end %>

  <% end %>

  <% @favourites.each do |n| %>
     
    <%if n.favourite_type == "favourite_blog"  %>
      <td><%= link_to n.user_blog.title ,user_blog_path(n.user_blog_id) %></td>
    <% end %>

  <%end%>

  <% @favourites.each do |n| %>
    <%if n.favourite_type == "favourite_carprofile"  %>
      <td><%= link_to n.carprofile.car_model.name ,carprofile_path(n.carprofile_id) %></td> 
    <% end %>
  </tr>

  <% end %>
</table>
</div>
<% end %>



</div>

app/views/home/logbooksearch_home.html.erb
<div class="middle">
    
    <div class="container_20" style="background:#333; margin-bottom:10px">
    <%= render 'shared/carousel' %>
    
    <div class="grid_20 title" style="margin-top:10px">
    
  <div style="width:40%; float:left"><h4>My Logbook</h4></div>
  <!-- <div style="width:40%; float:right; text-align:right; margin-top:5px"><a href="<%= new_logbook_path %>" class="compose">Add Logbook +</a></div> -->
  
  </div>
    
    <div class="grid_4">
    
    
    
      <ul class="message_menu">
    <li><%= link_to "All Logbook", logbooks_all_logbook_path rescue nil%></li>
    
    </ul>
    
    <strong class="bluelink">Topic</strong>
    <ul class="message_menu">
      <% @logbook_categories.each do |logbook| %>

        <li><%= link_to logbook.name, search_logbook_categories_path(:name => logbook.name ) %></li>
      <% end %>
    </ul>
    
    
    
      </div>
    
    <div class="grid_12">


    <% if @logbooks.empty? %>
     <%= "No logbook found" %>
    <%else%>
     <% @logbooks.each do |logbook| %>
      <%unless logbook.status == false %>
        <div class="message"> 
          <%unless logbook.carprofile.carprofile_photos.blank?%>
              <div class = "thumb"><%=link_to image_tag(logbook.carprofile.carprofile_photos.first.photo.url(:thumb) ,:width => 50, :height => 40) rescue nil%></div>
            <%else%>
              <div class = "thumb"><a href="#"><img src="/assets/index.jpeg" alt=""  width="50" height="40"></div>
            <%end%>
          <div class="mail_content" style="width:475px">
            <div><a href="<%=logbook_path(logbook)%>" class="bluelink bold"><%=logbook.title rescue nil%></a></div>
            <div style="margin:0 0 5px 0">by <a class="bluelink" href="<%=user_path(logbook.user_id)%>"><%=logbook.user.first_name rescue nil%></a></div>
            <div><%=sanitize raw(logbook.logbook_discription)[0..300], :tags => %w(b i u p br)  rescue nil %></div><br/>
            <div class="likediv"> <a href="<%=logbook_path(logbook)%>" class="likelink">Comment</a>  <% if logbook.created_at > Time.now.beginning_of_day %> 
                <%="#{time_ago_in_words(logbook.created_at)} ago"%>
              <% else %>
                <%= logbook.created_at.strftime("%b %d, %Y") %>
              <% end %>
            </div>
          </div>
        </div>
      <%else%>
        
      <%end%>
     <%end%>
    <%end%>
    
    
  <div class="digg_pagination">
   <%= will_paginate @logbooks %>
  </div>
    
    
    
    </div>
        
    <div class="grid_4">
    
    <div class="black_heading" style="margin-top:10px"> What Is Logbook</div>
  <div class="pe_box">
  
  

The Logbook is designed to record the events in the life of the respective car. In this section you can select the category and describe all modifications that you have made with your car. Logbook - All personal life of your vehicle. Equipment set, stories, performance modifications, improvements, photos e.t.c. 


</div>
    
    
      </div>
        
    
    </div>
    


  
    
    </div>
    

</div>

app/views/home/search.html.erb
<div class="middle">
  <div class="container_20" style="background:#333; margin-bottom:10px">
  <%= render 'shared/carousel' %></div>
 
 <div class="container_20">
  <div class="grid_20 title">
    <div style="width:40%; float:left"><h4>Search People</h4></div>
   </div>
    <div class="grid_20" style="overflow: auto; height: auto; margin: 10px 0px;">
      <% @users.each do |user|%>

    <div class="message" style="width:50%; float:left"> 
      <%= user.pic?  ? (image_tag user.pic.url(:thumb),:width => 100) : (image_tag 'thumb_profile.jpg',:width => 100)%>
    <div class="mail_content" style="width:auto">
    <% status = Block.find_by_blockable_id_and_blocker_id(current_user.id,user.id).present? %>
    <% if status %>
   <%= link_to user.first_name, "#",:id=>user.id,:class=>"bluelink bold",:onclick => "alert('You cannot access the Profile !!!');"%>&nbsp;&nbsp;<%= user.last_name %>
    <% else %>
    <%= link_to user.first_name, user_path(user),:id=>user.id,:class=>"bluelink bold" %> &nbsp;&nbsp;<%= user.last_name %>
    <% end %></br>   
     <div style="margin:0 0 5px 0"><% if user.about.nil? || user.about.blank? %>
    No Description Yet!
    <% else %>
    <%= truncate(user.about, :length => 50).html_safe  %>
    <% end %></br>
    <strong><%= user.location %></strong></div>
    </div>
 
    </div>
    <% end %>
    
    </div>
    
   </div>
   <div class="digg_pagination">
 <%= will_paginate @users %>
 </div>
 </div>

app/views/home/searchpeople.html.erb
<div style="min-height:400px" class="middle"></br>
<%= form_tag search_path, :method => :get do %>
  	
      <div style="text-align: center; margin-top: 100px;">
      	<h3 style="margin-bottom: 34px;">Search People</h3>

        <%= text_field_tag :user_cont,nil,:class => "search_people" %>
        <%= collection_select :country,:location_cont,Country.all(:order => :id) ,:name ,:name ,{:prompt => "Select a Country"} ,{:class => "search_country"} %>
        <%= submit_tag "Search",:class=>"submit_btn" %></div>
  <% end %>
  </br>
</div>
   

app/views/home/subscribe_count.html.erb
<%= stylesheet_link_tag  "table_style" %>
<div class="middle">
	<div class="grid_20 title">
		<h4 style="margin-top:10px;">Subscribers</h4>
		</div>

	<div class="grid_20" style="margin:10px;">	
<table width="100%">
<tr>
<th>First name</th>
<th>Last name</th>
<th>Email</th>
</tr>
<% @subscribers.each do |subscribe| %>
<tr>
<td><%=subscribe.first_name %></td>
<td><%=subscribe.last_name %></td>
<td><%=subscribe.email %></td>
</tr>
<% end %>
</table>
</div>

</div>

app/views/home/topcar.html.erb
<div class="middle">
  <div class="container_20" style="background:#333; margin-bottom:10px">
  <%= render 'shared/carousel' %></div>
 <div class="container_20">		
  <div class="grid_20 title">	
	<div style="width:40%; float:left"><h4>Top Car</h4></div>
  </div>		
 <!-- START MAIN LOOP FOR TOP CARS -->
 <div class="grid_20">
 	<!-- <p><%#= (page_entries_info @top_cars).gsub("arrays","top cars").html_safe %></p> -->
   <% @top_cars.each_with_index do |car,index| %>
   <% carprofile = Carprofile.find(car[0]) %>
	<div class="top_car_div" style="width:auto;"> 
	 		<div class="rank_car_div">
	 			<% unless carprofile.carprofile_photos.blank?%>
	 			
				  <%= image_tag carprofile.carprofile_photos.first.photo.url(:thumb), :width => 150, :height => 100 rescue nil  %></br>
				<%else%>
                  <a href="#"><img src="/assets/nullcar1.jpeg" alt="" width="150", height="100 "></a><br/>
                <%end%>
				<a href="#" class="bluelink bold"><%= carprofile.car_make.name%> <%= carprofile.car_model.name rescue nil%></a>
				<p class="<%= rate_count(carprofile.id)[0] rescue nil %>"></p>
			</div>
			<div class="rank_car_div2"> 
	 		<div style="width:auto; float:left"> 
				<div class="small_thumb">
					<%= carprofile.user.pic?  ? (image_tag carprofile.user.pic(:thumb),:style => "float:left",:width => 100, :height => 90) : (image_tag 'small_thumb.png')%>
					<!-- <img style="float:left" alt="" src="/assets/small_thumb.png"> -->
				</div>
				<div style="width:auto; float:left; width:175px" class="mail_content">
					<div><a><%= "#{carprofile.user.first_name} #{carprofile.user.last_name}".capitalize %></a></div>
		   			<div style="margin:0 0 5px 0"><% if carprofile.user.about.nil? || carprofile.user.about.blank? %>
                        No Description Yet!
                       <% else %>
                       <%= truncate(carprofile.user.about, :length => 30).html_safe  %>
                       <% end %></br>
		     			<strong><%= carprofile.user.location rescue nil%></strong>
	       			</div>
	       			
	    		</div>
			</div>
		</div>
        <div class="rank_car_div2" style="width:auto"> 
		<div class="rank_count"><%= @car_rank.index(car) + 1 %></div>
	       			<div style="clear:left; float:left"><a href="<%= carprofile_path(carprofile)%>"  class="submit_btn">Read More</a></div></div>
  	</div>
 <% end %>
 </div>
   <!-- <div class="digg_pagination">
 <%#= will_paginate @top_cars,:params => {:controller => "home",:action => "paginate_top_car" } %>
</div> -->
 <!-- STOP MAIN LOOP FOR TOP CARS -->
</div>
</div>
</div>