config/routes.rb
Drive::Application.routes.draw do

  resources :abuse_reports

  resources :manage_bodyindices do
    collection do
        delete 'destroy_multiple'
    end
  end

  resources :abuse_categories

  resources :contactadmins

  resources :messages do
    collection do
      get :trash_messages
      get :sent_messages
      put :move_all_to_trash_recipient
      put :delete_all_by_sender
    end
    
    member do
     post :trash
     post :destroy_recipient
     post :destroy_sender
     get :reply
    end
  end

 resources :friendships do
  member do
     post :accept
     post :decline
     post :delete
     post :cancel
  end
 end

 resources :shared do
    collection do
      get :search
      get :all_car
      get :car_body_index
    end
  end

  resources :blog_comments

  resources :notifications do 
    collection do
      get :noti_delete
    end
  end
  
  resources :comment_logs
  match "logbooks/:id/user_logbook"  => 'favourites#user_logbook'

  match "user_blogs/:id/user_blog"  => 'favourites#user_blog'

  match "carprofiles/:id/mycarprofile"  => 'favourites#mycarprofile'
 
  resources :comment_logbooks

  resources :user_blogs do
    collection do 
      post :like_blog
      get :like_count
      get :all_blogs
    end
  end

  resources :comments
  resources :new_cars
  resources :favourites do
    collection do
      get :deletefav
    end
  end

   resources :egifts ,:only => [:index] do
     resources :send_gifts
     collection do
      get :my_gifts
      get :anonymous
      get :personal
      get :egift_notifications
     end
   end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
  authenticated :user do
    root :to => 'home#index'
  end
  unauthenticated :user do
    root :to => 'devise/registrations#new'
  end
 end

  devise_for :admins

  resources :users,  :only => [:index,:destroy,:show,:subscribe_profile,:block_user,:unblock_user,:blocked_users,:change_status,:edit,:update,:new,:create] do
  collection    do
      post :subscribe_profile
      get  :user_emails
      post :block_user
      post :unblock_user
      get  :blocked_users
      post :change_status
      get :addpoints
      post :addedpoints
    end
   member do
      get :friend_request
      get :user_friends
      get :user_cars
      get :user_gifts
      get :user_blog
   end
  end
  

 
  match '/users/:id/toggled_status', :to => "users#toggled_status"

  match "/carprofiles/update_model", :to => "carprofiles#update_model"

  match "/carprofiles/update_body", :to => "carprofiles#update_body"

  match "/logbooks/updatemodel", :to => "logbooks#updatemodel"

  match "/logbooks/updatebody", :to => "logbooks#updatebody"

  match "/logbooks/all_logbook", :to => "logbooks#all_logbook"

  match '/pages/:id' => 'pages#show'

  match 'logbooksearch' => 'logbooks#logbooksearch'

  match 'blogsearch' => 'user_blogs#blogsearch'

  match "myfriend"  => 'logbooks#myfriend'

  match "/logbooksearch_home", :to => "home#logbooksearch_home"

  match "myfriend_blog"  => 'user_blogs#myfriend_blog'

  match "/carprofiles/comment_destroy", :to => "carprofiles#comment_destroy"

  match "/credits/get_credits" , :to => "credits#get_credits"

  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    match '/admin_mailer' => 'admin_mailers#admin_mailer'
    resources :pages
    resources :blogs
    resources :seos
    resources :car_makes
    resources :credits
    resources :car_models
    resources :logbook_categories
    resources :egift_categories
    resources :egifts
    resources :engines do 
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :body_indices
    resources :credit_packages
  end

  resources :credits do
    collection do
      get :earn_credits
      get :select_package
    end
  end
  resources :admincontacts
  resources :logbooks do 
    collection do 
      post :like_logbook
      get :like_count
      post :previews
    end
  end
  resources :carprofiles do
    collection do 
      post :like_car
      get :like_count
      post :subscribe_car
      post :spotlight
      post :post_comment
      get :guest_user
    end
  end 
  resources :carprofile_photos

 resources :logbook_categories do 
    get :search, :on => :collection
  end

  resources :blogs do 
    get :search_blog, :on => :collection
  end
 
  root :to => "devise/registrations#new"
   match 'subscribe_count' => 'home#subscribe_count'

  match 'subscar_count' =>'carprofiles#subscar_count'

  
  match '/contact' => 'home#contact'
  match 'search' => 'home#search'
  match 'searchpeople' => 'home#searchpeople'
  match 'keywordsearch' => 'home#keywordsearch'
  match 'topcar' => 'home#topcar'
  match 'paginate_top_car' => 'home#paginate_top_car'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :accepted_at, :friend_id,  :user_id,:flag
  belongs_to :user
  belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"
  validates_presence_of :user_id, :friend_id
  
  def self.exists?(user, friend)
   not find_by_user_id_and_friend_id(user, friend).nil?
  end


  def self.request(user, friend)
   unless user == friend or Friendship.exists?(user, friend)
    transaction do
      create(:user_id => user.id, :friend_id => friend.id, :flag => 'pending')
      create(:user_id => friend.id, :friend_id => user.id, :flag => 'requested')
    end
   end
  end

  # Accept a friend request.
  def self.accept(user, friend)
   transaction do
    accepted_at = Time.now
    accept_one_side(user, friend, accepted_at)
    accept_one_side(friend, user, accepted_at)
   end
  end

  # Delete a friendship or cancel a pending request.
  def self.breakup(user, friend)
   transaction do
    destroy(find_by_user_id_and_friend_id(user, friend))
    destroy(find_by_user_id_and_friend_id(friend, user))
   end
 end

private
# Update the db with one side of an accepted friendship request.
  def self.accept_one_side(user, friend, accepted_at)
	request = find_by_user_id_and_friend_id(user, friend)
	request.flag = 'accepted'
	request.accepted_at = accepted_at
	request.save!
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	include UsersHelper
    require 'will_paginate/array'
before_filter  :setup_friends,:except => :index

def index
	@friends = current_user.friends
	@requested_friends = current_user.requested_friends
	@pending_friends = current_user.pending_friends
end

def create
	Friendship.request(@user, @friend)
	#raise @friend.id.inspect
	@notification = Notification.new(:user_id => current_user.id, :notification_type => "friendship", :notifiable_id  => @friend.id)
	@notification.save
	flash[:notice] = "Friend request sent."
	redirect_to(:back)
end

def accept
	if @user.requested_friends.include?(@friend)
	Friendship.accept(@user, @friend)
	flash[:notice] = "Friendship with #{@friend.nickname} accepted!"
	else
	flash[:notice] = "No friendship request from #{@friend.nickname}."
	end
	redirect_to(:back)
end

def decline
	if @user.requested_friends.include?(@friend)
	Friendship.breakup(@user, @friend)
	flash[:notice] = "Friendship with #{@friend.nickname} declined"
	else
	flash[:notice] = "No friendship request from #{@friend.nickname}."
	end
	redirect_to(:back)
end

def cancel
if @user.pending_friends.include?(@friend)
 Friendship.breakup(@user, @friend)
  flash[:notice] = "Friendship request canceled."
  else
  flash[:notice] = "No request for friendship with #{@friend.nickname}"
 end
 redirect_to(:back)
end


def delete
 if @user.friends.include?(@friend)
  Friendship.breakup(@user, @friend)
  flash[:notice] = "Friendship with #{@friend.nickname} deleted!"
 else
  flash[:notice] = "You aren't friends with #{@friend.nickname}"
 end
redirect_to(:back)
end


private

def setup_friends
	@user = current_user
	@friend = User.find(params[:id])
end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

def friendship_status(user, friend)
  friendship = Friendship.find_by_user_id_and_friend_id(user, friend)
  return "#{friend.nickname} is not your friend (yet)." if friendship.nil?
  case friendship.flag
    when 'requested'
     "#{friend.nickname} would like to be your friend."
    when 'pending'
     "Friendship requested"
    when 'accepted'
     "#{friend.nickname} is your friend."
    end
  end

end
  

app/views/friendships/index.html.erb
<div class="middle">
    
    <div class="container_20" style="background:#333; margin-bottom:10px">
    
    
    </div>
    
    
        <div class="container_20">
        
        
        <div class="grid_20 title">
    
  <div style="width:40%; float:left"><h4>Friends</h4></div>
  <!-- <div style="width:40%; float:right; text-align:right; margin-top:5px"><a href="#" class="compose">Create a List </a></div> -->
  
  
  
    
    
    </div>
    
    <div class="grid_4">
    
    
    
      <ul class="message_menu">
    <li><%= link_to "All Friends", friendships_path %></li>
    <li><%= link_to "Incomming Requests", friend_request_user_path(current_user) %></li>
    <li><%= link_to "Pending Requests", friend_request_user_path(current_user,:type => "Pending") %></li>
    </ul>
    
    
    
      </div>
    
    <div class="grid_16">
     
    
    <!-- <div><input name="" type="text" class="pe_tf message_search"></div> -->
     <% current_user.friends.each do |friend|%>
    <% unless Block.status(current_user,friend) %>
    <div class="message"> 
    
    <div class="tf">
    <!-- <input name="" type="checkbox" value=""> -->
    
    
    </div>
    <%if friend.pic.blank? %>
    <a href="<%= user_path(friend)%>"><img src="assets/thumb_profile.jpg" alt="">
    <%else%>
    <%= link_to image_tag(friend.pic.url(:thumb),:width => 50, :height => 40), user_path(friend)%>
    <% end %>
    <div class="mail_content">
    <div><a href="<%= user_path(friend)%>" class="bluelink bold"><b><%=friend.first_name %> <%= friend.last_name%></b></a></div>
    
    
    </div>
    
    
    
    <ul class="action">
    
    
    <li><li><%= link_to (image_tag "delete.png"),delete_friendship_path(:id => friend.id) ,:method => :post,:confirm => "Are you sure, you want to remove #{friend.email}?" %></li></li>
    
    </ul>
    
    
    
    </div>
    <%end%>
    <% end %>
    
    
    <!-- <ul class="tsc_pagination tsc_paginationA tsc_paginationA01">
      <%#= will_paginate @friends %>
    </ul> -->
    
    
    
    </div>
        
    
        
    
    </div>
    


  
    
    </div>
    

</div>