config/routes.rb
Drive::Application.routes.draw do

  resources :abuse_reports

  resources :manage_bodyindices do
    collection do
        delete 'destroy_multiple'
    end
  end

  resources :abuse_categories

  resources :contactadmins

  resources :messages do
    collection do
      get :trash_messages
      get :sent_messages
      put :move_all_to_trash_recipient
      put :delete_all_by_sender
    end
    
    member do
     post :trash
     post :destroy_recipient
     post :destroy_sender
     get :reply
    end
  end

 resources :friendships do
  member do
     post :accept
     post :decline
     post :delete
     post :cancel
  end
 end

 resources :shared do
    collection do
      get :search
      get :all_car
      get :car_body_index
    end
  end

  resources :blog_comments

  resources :notifications do 
    collection do
      get :noti_delete
    end
  end
  
  resources :comment_logs
  match "logbooks/:id/user_logbook"  => 'favourites#user_logbook'

  match "user_blogs/:id/user_blog"  => 'favourites#user_blog'

  match "carprofiles/:id/mycarprofile"  => 'favourites#mycarprofile'
 
  resources :comment_logbooks

  resources :user_blogs do
    collection do 
      post :like_blog
      get :like_count
      get :all_blogs
    end
  end

  resources :comments
  resources :new_cars
  resources :favourites do
    collection do
      get :deletefav
    end
  end

   resources :egifts ,:only => [:index] do
     resources :send_gifts
     collection do
      get :my_gifts
      get :anonymous
      get :personal
      get :egift_notifications
     end
   end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
  authenticated :user do
    root :to => 'home#index'
  end
  unauthenticated :user do
    root :to => 'devise/registrations#new'
  end
 end

  devise_for :admins

  resources :users,  :only => [:index,:destroy,:show,:subscribe_profile,:block_user,:unblock_user,:blocked_users,:change_status,:edit,:update,:new,:create] do
  collection    do
      post :subscribe_profile
      get  :user_emails
      post :block_user
      post :unblock_user
      get  :blocked_users
      post :change_status
      get :addpoints
      post :addedpoints
    end
   member do
      get :friend_request
      get :user_friends
      get :user_cars
      get :user_gifts
      get :user_blog
   end
  end
  

 
  match '/users/:id/toggled_status', :to => "users#toggled_status"

  match "/carprofiles/update_model", :to => "carprofiles#update_model"

  match "/carprofiles/update_body", :to => "carprofiles#update_body"

  match "/logbooks/updatemodel", :to => "logbooks#updatemodel"

  match "/logbooks/updatebody", :to => "logbooks#updatebody"

  match "/logbooks/all_logbook", :to => "logbooks#all_logbook"

  match '/pages/:id' => 'pages#show'

  match 'logbooksearch' => 'logbooks#logbooksearch'

  match 'blogsearch' => 'user_blogs#blogsearch'

  match "myfriend"  => 'logbooks#myfriend'

  match "/logbooksearch_home", :to => "home#logbooksearch_home"

  match "myfriend_blog"  => 'user_blogs#myfriend_blog'

  match "/carprofiles/comment_destroy", :to => "carprofiles#comment_destroy"

  match "/credits/get_credits" , :to => "credits#get_credits"

  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    match '/admin_mailer' => 'admin_mailers#admin_mailer'
    resources :pages
    resources :blogs
    resources :seos
    resources :car_makes
    resources :credits
    resources :car_models
    resources :logbook_categories
    resources :egift_categories
    resources :egifts
    resources :engines do 
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :body_indices
    resources :credit_packages
  end

  resources :credits do
    collection do
      get :earn_credits
      get :select_package
    end
  end
  resources :admincontacts
  resources :logbooks do 
    collection do 
      post :like_logbook
      get :like_count
      post :previews
    end
  end
  resources :carprofiles do
    collection do 
      post :like_car
      get :like_count
      post :subscribe_car
      post :spotlight
      post :post_comment
      get :guest_user
    end
  end 
  resources :carprofile_photos

 resources :logbook_categories do 
    get :search, :on => :collection
  end

  resources :blogs do 
    get :search_blog, :on => :collection
  end
 
  root :to => "devise/registrations#new"
   match 'subscribe_count' => 'home#subscribe_count'

  match 'subscar_count' =>'carprofiles#subscar_count'

  
  match '/contact' => 'home#contact'
  match 'search' => 'home#search'
  match 'searchpeople' => 'home#searchpeople'
  match 'keywordsearch' => 'home#keywordsearch'
  match 'topcar' => 'home#topcar'
  match 'paginate_top_car' => 'home#paginate_top_car'

end

app/models/credit_package.rb
class CreditPackage < ActiveRecord::Base
  attr_accessible :name,:package_type,:points_field, :amount, :custom_field, :link
  validates_presence_of :points_field, :amount, :custom_field, :link

end

app/controllers/admin/credit_packages_controller.rb
class Admin::CreditPackagesController < ApplicationController
  before_filter :authenticate_admin!, :except => []
  layout 'admin'

  def index
  	@credit_packages = CreditPackage.all
  	@credit = Credit.first
	    if @credit.nil?
	      @credit = Credit.new(:credit => 0, :free_credit => 0)
	      @credit.save
	    end
	    @credit_package = CreditPackage.new
	    @credit_packages = CreditPackage.all
  end

  def new
  	@credit_package = CreditPackage.new
  end

  def show
    @credit_package = CreditPackage.find(params[:id])
  end

  def create
    @credit_package = CreditPackage.new(params[:credit_package])
    if @credit_package.save
	 	flash[:notice] = "Credit Package Created Successfully"
        redirect_to admin_credit_packages_path
    else
        render :new
    end
  end

  def edit
      @credit_package = CreditPackage.find(params[:id])
      #raise @credit_package.inspect
    end

    def update
      @credit_package = CreditPackage.find(params[:id])
      if @credit_package.update_attributes(params[:credit_package])
        flash[:notice] = "Credit Package Saved Successfully"
        redirect_to admin_credit_packages_path
      else
        render :new
      end
    end
    

    def destroy
      @credit_package = CreditPackage.find(params[:id])
     
      if @credit_package.destroy
        flash[:notice] = "Credit Package Deleted Successfully"
        redirect_to admin_credit_packages_path
      end
      
    end
end

app/helpers/admin/credit_packages_helper.rb
module Admin::CreditPackagesHelper
end

app/views/admin/credit_packages/_form.html.erb
  
  <% if @credit_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_package.errors.count, "error") %> prohibited this car model from being saved:</h2>

      <ul>
      <% @credit_package.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Points_To_Be_Added  %>
    (Example: Simply add how much points user can buy. Remember only integer value should be entered, eg: 10 )<br/>
    <%= f.text_field :points_field %>
  </div><br/>


  <div class="field">
    <%= f.label :Amount_Of_Point  %>(Example: Add amount of package, eg: 1 USD)<br/>
    <%= f.text_field :amount %>
  </div><br/>

  <div class="field">
    <%= f.label :Custom_Field  %>(Example: This field is used as code,this tell application to increase the points of user. eg code: 1001)<br/>
    <%= f.text_field :custom_field %>
  </div><br/>

  <div class="field">
    <%= f.label :Link  %>(Example: This is the BuyNow URL link generated after product registration you can find this BuyNow URL link in contract general information, 
    eg: you will see this type of URL => href='https://www.plimus.com/jsp/buynow.jsp?contractId=3222914, simply add this in text field )<br/>
    <%= f.text_area :link %>
  </div>

app/views/admin/credit_packages/edit.html.erb
<%= form_for [:admin, @credit_package]  do |f| %>

   <%= render 'form' ,:f => f %>
    <div class="actions">
    <%= f.submit  "Update Credit Package" %>
  </div>
 <% end %>

app/views/admin/credit_packages/index.html.erb
<%= link_to 'Add Credit Package', new_admin_credit_package_path %>
<br /><br />
<table class="admintable">
 <tr class="admintablehd">
    <td width="25%">Package Name</td>
     <td width="25%">Package Amount</td>
     
   <td colspan=3 style="text-align: center !important;">Actions</td>
</tr>

<% @credit_packages.each do |credit_package|%>
  <tr>
    <td><%= credit_package.points_field %> Points </td>
    <td><%= credit_package.amount %></td>
    <td style="text-align: center !important;"><%= link_to 'Edit', edit_admin_credit_package_path(credit_package) %></td>
    <td style="text-align: center !important;"><%= link_to 'Show', admin_credit_package_path(credit_package) %></td>
    <td style="text-align: center !important;"><%= link_to 'Destroy',admin_credit_package_path(credit_package) ,:method => :delete , :data=>{ :confirm=> 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<%= render '/admin/credits/index'%>

app/views/admin/credit_packages/new.html.erb
<%= form_for [:admin, @credit_package]  do |f| %>
   <%= render '/admin/credit_packages/form' ,:f => f %>
    <div class="actions">
    <%= f.submit  "Create Credit Package" %>
  </div>
 <% end %>

app/views/admin/credit_packages/show.html.erb
<p><%= notice %></p>

<p>
  <b>Points to be added:</b>
  <%= @credit_package.points_field %>
</p>

<p>
  <b>Amount of credit:</b>
  <%= @credit_package.amount %>
</p>

<p>
  <b>Custom Id :</b>
  <%= @credit_package.custom_field %>
</p>

<p>
  <b>Link of Product:</b>
  <%= @credit_package.link %>
</p>


<%#= link_to 'Back', admincontacts_path %>