config/routes.rb
Drive::Application.routes.draw do

  resources :abuse_reports

  resources :manage_bodyindices do
    collection do
        delete 'destroy_multiple'
    end
  end

  resources :abuse_categories

  resources :contactadmins

  resources :messages do
    collection do
      get :trash_messages
      get :sent_messages
      put :move_all_to_trash_recipient
      put :delete_all_by_sender
    end
    
    member do
     post :trash
     post :destroy_recipient
     post :destroy_sender
     get :reply
    end
  end

 resources :friendships do
  member do
     post :accept
     post :decline
     post :delete
     post :cancel
  end
 end

 resources :shared do
    collection do
      get :search
      get :all_car
      get :car_body_index
    end
  end

  resources :blog_comments

  resources :notifications do 
    collection do
      get :noti_delete
    end
  end
  
  resources :comment_logs
  match "logbooks/:id/user_logbook"  => 'favourites#user_logbook'

  match "user_blogs/:id/user_blog"  => 'favourites#user_blog'

  match "carprofiles/:id/mycarprofile"  => 'favourites#mycarprofile'
 
  resources :comment_logbooks

  resources :user_blogs do
    collection do 
      post :like_blog
      get :like_count
      get :all_blogs
    end
  end

  resources :comments
  resources :new_cars
  resources :favourites do
    collection do
      get :deletefav
    end
  end

   resources :egifts ,:only => [:index] do
     resources :send_gifts
     collection do
      get :my_gifts
      get :anonymous
      get :personal
      get :egift_notifications
     end
   end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  devise_scope :user do
  authenticated :user do
    root :to => 'home#index'
  end
  unauthenticated :user do
    root :to => 'devise/registrations#new'
  end
 end

  devise_for :admins

  resources :users,  :only => [:index,:destroy,:show,:subscribe_profile,:block_user,:unblock_user,:blocked_users,:change_status,:edit,:update,:new,:create] do
  collection    do
      post :subscribe_profile
      get  :user_emails
      post :block_user
      post :unblock_user
      get  :blocked_users
      post :change_status
      get :addpoints
      post :addedpoints
    end
   member do
      get :friend_request
      get :user_friends
      get :user_cars
      get :user_gifts
      get :user_blog
   end
  end
  

 
  match '/users/:id/toggled_status', :to => "users#toggled_status"

  match "/carprofiles/update_model", :to => "carprofiles#update_model"

  match "/carprofiles/update_body", :to => "carprofiles#update_body"

  match "/logbooks/updatemodel", :to => "logbooks#updatemodel"

  match "/logbooks/updatebody", :to => "logbooks#updatebody"

  match "/logbooks/all_logbook", :to => "logbooks#all_logbook"

  match '/pages/:id' => 'pages#show'

  match 'logbooksearch' => 'logbooks#logbooksearch'

  match 'blogsearch' => 'user_blogs#blogsearch'

  match "myfriend"  => 'logbooks#myfriend'

  match "/logbooksearch_home", :to => "home#logbooksearch_home"

  match "myfriend_blog"  => 'user_blogs#myfriend_blog'

  match "/carprofiles/comment_destroy", :to => "carprofiles#comment_destroy"

  match "/credits/get_credits" , :to => "credits#get_credits"

  namespace :admin do 
    match '/dashboard' => "dashboard#index", :as => :root
    match '/admin_mailer' => 'admin_mailers#admin_mailer'
    resources :pages
    resources :blogs
    resources :seos
    resources :car_makes
    resources :credits
    resources :car_models
    resources :logbook_categories
    resources :egift_categories
    resources :egifts
    resources :engines do 
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :body_indices
    resources :credit_packages
  end

  resources :credits do
    collection do
      get :earn_credits
      get :select_package
    end
  end
  resources :admincontacts
  resources :logbooks do 
    collection do 
      post :like_logbook
      get :like_count
      post :previews
    end
  end
  resources :carprofiles do
    collection do 
      post :like_car
      get :like_count
      post :subscribe_car
      post :spotlight
      post :post_comment
      get :guest_user
    end
  end 
  resources :carprofile_photos

 resources :logbook_categories do 
    get :search, :on => :collection
  end

  resources :blogs do 
    get :search_blog, :on => :collection
  end
 
  root :to => "devise/registrations#new"
   match 'subscribe_count' => 'home#subscribe_count'

  match 'subscar_count' =>'carprofiles#subscar_count'

  
  match '/contact' => 'home#contact'
  match 'search' => 'home#search'
  match 'searchpeople' => 'home#searchpeople'
  match 'keywordsearch' => 'home#keywordsearch'
  match 'topcar' => 'home#topcar'
  match 'paginate_top_car' => 'home#paginate_top_car'

end

app/models/egift.rb
class Egift < ActiveRecord::Base
  attr_accessible :credit,:image,:egift_category_id
  validates_presence_of :credit,:image
  belongs_to :egift_category
  has_attached_file :image, :styles => { :thumb => "100x100", :medium => "350x350"},
                   :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml",
                    :path => "public/attachments/egift/:id/:style/:basename.:extension",
                    
                    :convert_options => {
                          :thumb => "-compose Copy -gravity center -extent 100x100",
                          :medium => "-compose Copy -gravity center -extent 350x350",
                          
                      }
end

app/controllers/admin/egifts_controller.rb
class Admin::EgiftsController < ApplicationController
 before_filter :authenticate_admin!, :except => []
  layout 'admin'

  def index
  	@egifts = Egift.all
  end

  def new
  	@egift = Egift.new
  end

  def create
    @egift = Egift.new(params[:egift])
    if @egift.save
	 	flash[:notice] = "Egift Created Successfully"
        redirect_to admin_egifts_path
    else
        render :new
    end
  end

  def edit
      @egift = Egift.find(params[:id])
    end

    def update
      @egift = Egift.find(params[:id])
      if @egift.update_attributes(params[:egift])
        flash[:notice] = "Egift Saved Successfully"
        redirect_to admin_egifts_path
      else
        render :new
      end
    end
    

    def destroy
      @egift = Egift.find(params[:id])
     
      if @egift.destroy
        flash[:notice] = "Egift Deleted Successfully"
        redirect_to admin_egifts_path
      end
      
    end
end

app/controllers/egifts_controller.rb
require 'will_paginate/array'

class EgiftsController < ApplicationController
before_filter :authenticate_user!
  def index
  	@egifts = Egift.all
  	@category = EgiftCategory.all
    @send_gift = SendGift.new

  end
  
  def my_gifts
  	@send_gifts = current_user.received_egifts
    @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
  	@public = @send_gifts.public_gift.paginate(page: params[:page], per_page: 5) 
  end

  def anonymous
    @send_gifts = current_user.received_egifts
    @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
    @anon = @send_gifts.anonymous.paginate(page: params[:page], per_page: 5) 
  end

  def personal
    @send_gifts = current_user.received_egifts
    @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
    @personal = @send_gifts.personal.paginate(page: params[:page], per_page: 5) 
  end

  def egift_notifications
    @send_gifts = current_user.received_egifts
    @public = @send_gifts.public_gift2 
    @anon = @send_gifts.anonymous2
    @personal = @send_gifts.personal2
    @spotlighted_cars = Carprofile.where("spotlighted = ?",true)
  end

end

app/helpers/admin/egifts_helper.rb
module Admin::EgiftsHelper
end

app/helpers/egifts_helper.rb
module EgiftsHelper
end

app/views/egifts/_form.html.erb
<style>
.field{
color: black;

}
</style>

<%= form_for([egift,@send_gift]) do |f| %>
  <% if @send_gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@send_gift.errors.count, "error") %> prohibited this send_gift from being saved:</h2>

      <ul>
      <% @send_gift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :rows => 5 ,:cols => 60 %>
  </div>
    <%= f.hidden_field :egift_id ,:value => egift.id %>
   <%= f.hidden_field :sender_id ,:value => current_user.id %><br/>
    <%= f.hidden_field :carprofile_id ,:value => params[:carprofile_id] %>

    <% a =  Carprofile.find(params[:carprofile_id]).user_id  rescue nil%>
     <%= f.hidden_field :receiver_id ,:value => a %>
  <div class="actions">
    <%= f.submit "Send" %>
  </div>
<% end %>

app/views/egifts/anonymous.html.erb
<div class="middle">
      <div class="container_20" style="background:#333; margin-bottom:10px">
  <%= render 'shared/carousel' %>   
  </div>
    <div class="container_20">
     <div class="grid_4">
    
    
    
      <ul class="message_menu">
    <li><%= link_to "Public", my_gifts_egifts_path %></li>
    <li><%= link_to "Personal", personal_egifts_path %></li>
    <li class="selected" ><%= link_to "Anonymous", anonymous_egifts_path %></li>
    </ul>
    
    
      </div>
    <div class="grid_16">
  <h4>Anonymous</h4>

     <% @anon.each do |g|%>

  <div class="message">
 <table width="100%" border="0" cellspacing="5" cellpadding="5">
  <tr>
    <td align="left" valign="top" width="150px"><strong>Sender</strong></td>
    <td align="left" valign="top" >Anonymous</td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Message</strong></td>
    <td align="left" valign="top"><%= g.message %></td>
    </tr>
    <tr>
    <td align="left" valign="top"><strong>Car</strong></td>
    <td align="left" valign="top"><%= g.carprofile.car_model.name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Gift</strong></td>
    <td align="left" valign="top"><%= image_tag g.egift.image.url(:thumb) ,:class =>"giftimage" %> </td>
    </tr>
    <tr>
    <td align="left" valign="top"><strong></strong></td>
    <td align="left" valign="top"><%= link_to 'Destroy',  egift_send_gift_path(g,g), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
</table>

  
  </div>
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @anon, :container => false %>
  </div>
</div>
</div>
</div>

app/views/egifts/egift_notifications.html.erb
<div class="middle">
      <div class="container_20" style="background:#333; margin-bottom:10px">
  <%#= render 'shared/carousel' %>   
  </div>
    <div class="container_20">
        

    
    <div class="grid_16">
    
   <h4>Public</h4>
    <% @public.each do |g|%>

  <div class="message">

 <table width="100%" border="0" cellspacing="5" cellpadding="5">
  <tr>
    <td align="left" valign="top" width="150px"><strong>Sender</strong></td>
    <td align="left" valign="top" ><%= g.sender.first_name %> <%= g.sender.last_name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Message</strong></td>
    <td align="left" valign="top"><%= g.message %></td>
  </tr>
<tr>
    <td align="left" valign="top"><strong>Car</strong></td>
    <td align="left" valign="top"><%= g.carprofile.car_model.name %></td>
    </tr>
  
  <tr>
    <td align="left" valign="top"><strong>Gift</strong></td>
    <td align="left" valign="top"><%= image_tag g.egift.image.url(:thumb) ,:class =>"giftimage" %> </td>
    </tr>

   <tr>
    <td align="left" valign="top"><strong></strong></td>
    <td align="left" valign="top">
    <%= link_to 'Accept',  egift_send_gift_path(g,g),method: :put %>
    <%= link_to 'Reject',  egift_send_gift_path(g,g), method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    </tr>
</table>

  
  </div>
  <% end %>

 
  </div>

    <div class="grid_16">
<h4>Personal</h4>

     <% @personal.each do |g|%>

  <div class="message">
 <table width="100%" border="0" cellspacing="5" cellpadding="5">
  <% if current_user == g.sender || current_user == g.receiver %>
  <tr>
    <td align="left" valign="top" width="150px"><strong>Sender</strong></td>
    <td align="left" valign="top" ><%= g.sender.first_name %> <%= g.sender.last_name %></td>
   </tr>
  <tr>
    <td align="left" valign="top"><strong>Message</strong></td>
    <td align="left" valign="top"><%= g.message %></td>
    </tr>
   <% end %>
    <tr>
    <td align="left" valign="top"><strong>Car</strong></td>
    <td align="left" valign="top"><%= g.carprofile.car_model.name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Gift</strong></td>
    <td align="left" valign="top"><%= image_tag g.egift.image.url(:thumb) ,:class =>"giftimage" %> </td>
    </tr>
    <tr>
    <td align="left" valign="top"><strong></strong></td>
    <td align="left" valign="top">
      <%= link_to 'Accept',  egift_send_gift_path(g,g),method: :put %>
    <%= link_to 'Reject',  egift_send_gift_path(g,g), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
</table>

  
  </div>
  <% end %>

  
  </div>

      <div class="grid_16">
  <h4>Anonymous</h4>

     <% @anon.each do |g|%>

  <div class="message">
 <table width="100%" border="0" cellspacing="5" cellpadding="5">
  <tr>
    <td align="left" valign="top" width="150px"><strong>Sender</strong></td>
    <td align="left" valign="top" >Anonymous</td>
    </tr>
  <% if current_user == g.sender || current_user == g.receiver %>
  <tr>
    <td align="left" valign="top"><strong>Message</strong></td>
    <td align="left" valign="top"><%= g.message %></td>
   </tr>
  <% end %>
    <tr>
    <td align="left" valign="top"><strong>Car</strong></td>
    <td align="left" valign="top"><%= g.carprofile.car_model.name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Gift</strong></td>
    <td align="left" valign="top"><%= image_tag g.egift.image.url(:thumb) ,:class =>"giftimage" %> </td>
    </tr>
    <tr>
    <td align="left" valign="top"><strong></strong></td>
    <td align="left" valign="top">
      <%= link_to 'Accept',  egift_send_gift_path(g,g),method: :put %>
    <%= link_to 'Reject',  egift_send_gift_path(g,g), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
</table>

  
  </div>
  <% end %>

</div>

</div>
</div>

app/views/egifts/index.html.erb
 <%= stylesheet_link_tag "jquery.fancybox" %>

 <%= javascript_include_tag "jquery.fancybox.pack" %>
 <script type="text/javascript">
 jQuery.noConflict();
		jQuery(document).ready(function() {
		<% @egifts.each do |egift| %>
			jQuery("#various<%= egift.id%>").fancybox({
				'titlePosition'		: 'inside',
				'transitionIn'		: 'none',
				'transitionOut'		: 'none'
			});
			<% end %>
			

					});
	</script>


<div class="middle">

				<div class="container_20">
				
				
				<div class="grid_20 title">
		
	<h4>Send a Gift</h4>
	
	
	
	
		
		
		</div>
		
		
		<div class="grid_20">
		
	
		<div class="clearfix" id="w">
    <ul id="sidemenu">
      <li style="border-top:1px solid #E7E7E7">
        <a class="open" href="#home-content">All Gifts</a>
      </li>
      <% @category.each do |category| %>
      <li>
        <a href="#about-content<%= category.id %>"><%= category.name %></a>
      </li>
      <% end %>
    </ul>
    
    <div id="content">
        <div class="contentblock" id="home-content">
		
		
          <div id="mainwrapper">
		<% @egifts.each do |egift| %>
		<div id="box-1" class="box1">
			<a href="#inline<%= egift.id %>" id="various<%= egift.id %>">
			
			 <%= image_tag egift.image.url %></a>
				<span class="caption simple-caption">
					<p><%#= link_to "Send" ,new_send_gift_path(egift,:carprofile_id => params[:carprofile_id]) %></p>
				</span>
		</div>
			<div style="display: none ">
		
		<div id="inline<%= egift.id %>" style="width:650px; height:auto ; overflow:auto; text-align:left">
		<div>

		<div class="fancybox_title">Send a Gift</div>

		<div  style="padding:50px 10px">
				<%= render 'send_gifts/form' ,:egift => egift %>
		

		</div>
     </div>
   </div>
</div>

		<% end %>
		
		
		
	</div>
     </div>
        
         <% @category.each do |c| %>
        <div class="contentblock hidden" id="about-content<%= c.id %>">
         <div id="mainwrapper">
         	<% c.egifts.each do |g| %>
         			<div id="box-1" class="box1">
         	<a href="#inline<%= g.id %>" id="various<%= g.id %>">

			<%= image_tag g.image.url %></a>
				<span class="caption simple-caption">
					<p><%#= link_to "Send" ,new_send_gift_path(g, :carprofile_id => params[:carprofile_id]) %></p>
				</span>
		  </div>

		  	<div style="display: none  ">
		<%= g.id %>
		<div id="inline<%= g.id %>" style="width:650px; height:auto ; overflow:auto; text-align:left">
		<div>

		<div class="fancybox_title">Send a Gift</div>

		<div  style="padding:50px 10px">
				<%= render 'form' ,:egift => g %>
		

		</div>
     </div>
   </div>
</div>
         	<%end %>
	
		
	


		
	</div>
      
        </div>
<% end %>


    </div>
  </div>
	
	
	
	
		
		
		</div>
		
		
		
				
		
				
		
		</div>

<script type="text/javascript">
jQuery(function(){
  jQuery('#sidemenu a').on('click', function(e){
    e.preventDefault();

    if(jQuery(this).hasClass('open')) {
      // do nothing because the link is already open
    } else {
      var oldcontent = jQuery('#sidemenu a.open').attr('href');
      var newcontent = jQuery(this).attr('href');
      
      jQuery(oldcontent).fadeOut('fast', function(){
        jQuery(newcontent).fadeIn().removeClass('hidden');
        jQuery(oldcontent).addClass('hidden');
      });
      
     
      jQuery('#sidemenu a').removeClass('open');
      jQuery(this).addClass('open');
    }
  });
});
</script>

app/views/egifts/my_gifts.html.erb
<div class="middle">
      <div class="container_20" style="background:#333; margin-bottom:10px">
  <%= render 'shared/carousel' %>   
  </div>
    <div class="container_20">
        
    <div class="grid_4">
      <ul class="message_menu">
      <li  class="selected" ><%= link_to "Public", my_gifts_egifts_path %></li>
      <li><%= link_to "Personal", personal_egifts_path %></li>
      <li><%= link_to "Anonymous", anonymous_egifts_path %></li>
      </ul>
    </div>
    
    <div class="grid_16">
    
   <h4>Public</h4>
    <% @public.each do |g|%>

  <div class="message">

 <table width="100%" border="0" cellspacing="5" cellpadding="5">
  <tr>
    <td align="left" valign="top" width="150px"><strong>Sender</strong></td>
    <td align="left" valign="top" ><%= g.sender.first_name %> <%= g.sender.last_name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Message</strong></td>
    <td align="left" valign="top"><%= g.message %></td>
  </tr>
<tr>
    <td align="left" valign="top"><strong>Car</strong></td>
    <td align="left" valign="top"><%= g.carprofile.car_model.name %></td>
    </tr>
  
  <tr>
    <td align="left" valign="top"><strong>Gift</strong></td>
    <td align="left" valign="top"><%= image_tag g.egift.image.url(:thumb) ,:class =>"giftimage" %> </td>
    </tr>
<tr>
    <td align="left" valign="top"><strong></strong></td>
    <td align="left" valign="top"><%= link_to 'Destroy',  egift_send_gift_path(g,g), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
</table>

  
  </div>
  <% end %>
  
  <div class="digg_pagination">
    <%= will_paginate @public, :container => false %>
  </div>
 
  </div>
</div>
</div>

app/views/egifts/personal.html.erb
<div class="middle">
      <div class="container_20" style="background:#333; margin-bottom:10px">
  <%= render 'shared/carousel' %>   
  </div>
    <div class="container_20">
     <div class="grid_4">
    
    
    
      <ul class="message_menu">
    <li><%= link_to "Personal", my_gifts_egifts_path %></li>
    <li  class="selected"><%= link_to "Personal", personal_egifts_path %></li>
    <li><%= link_to "Anonymous", anonymous_egifts_path %></li>
    </ul>
    
    
      </div>
    <div class="grid_16">
<h4>Personal</h4>

     <% @personal.each do |g|%>

  <div class="message">
 <table width="100%" border="0" cellspacing="5" cellpadding="5">
  <tr>
    <td align="left" valign="top" width="150px"><strong>Sender</strong></td>
    <td align="left" valign="top" ><%= g.sender.first_name %> <%= g.sender.last_name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Message</strong></td>
    <td align="left" valign="top"><%= g.message %></td>
    </tr>
    <tr>
    <td align="left" valign="top"><strong>Car</strong></td>
    <td align="left" valign="top"><%= g.carprofile.car_model.name %></td>
    </tr>
  <tr>
    <td align="left" valign="top"><strong>Gift</strong></td>
    <td align="left" valign="top"><%= image_tag g.egift.image.url(:thumb) ,:class =>"giftimage" %> </td>
    </tr>
    <tr>
    <td align="left" valign="top"><strong></strong></td>
    <td align="left" valign="top"><%= link_to 'Destroy',  egift_send_gift_path(g,g), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
</table>

  
  </div>
  <% end %>

  <div class="digg_pagination">
    <%= will_paginate @personal, :container => false %>
  </div>
  
  </div>
</div>
</div>